### ISSUE TITLE
Permissions are being messed up after backing up the rootfs

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/proot-distro#47] opened 2020-12-11 13:14 UTC
Hello, so recently i did a backup of clean archlinux Installation and after backing up, it gives errors about sudo that the permissions are not set properly

And it gives warnings about permissions is not correct

Warnings about pacman:
```
warning: directory permissions differ on /usr/lib/pkgconfig/
filesystem: 700  package: 755

```

Warnings about sudo:
```
sudo: /etc/sudo.conf is owned by uid 10873, should be 0
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```

Is it okay if permissions are retained?

**Comment by xeffyr** [comment] 2020-12-11 13:43
That's intended behavior. Permissions are being changed on this basis:
* Directories: 700
* Executables: 700
* Regular files: 600

IOk, I can change it to just ensure that at least user has rw/rwx access and not force reset permissions for everything. Will be fixed in 1.3.2.

**Closed by xeffyr** 2020-12-11 13:43 UTC
