### ISSUE TITLE
add CentOS

### ISSUE THREAD

**Issue by johnss** [termux/proot-distro#58] opened 2021-01-31 11:50 UTC
I need centos 7 and also old ubuntu 14, is it possible to add distro manually without waiting the developer to add it, if so please create a tutorial how to add it!

**Comment by WMCB-Tech** [comment] 2021-01-31 12:08
Ubuntu 14.04 may not be added, i have problems running Ubuntu 14.04 (dpkg fails if symlink has changed size)

**Comment by ZhymabekRoman** [comment] 2021-02-01 03:09
> i have problems running Ubuntu 14.04 (dpkg fails if symlink has changed size)

Have you tried to add the -L flag for proot during the launch of Ubuntu 14? In theory, this should fix problomes with dpkg that you have.
```-L    Correct the size returned from lstat for symbolic links.```

**Comment by ZhymabekRoman** [comment] 2021-02-01 03:13
> I need centos 7

IMHO, this makes no sense, support for CentOS 7 will soon end this year, and Ubuntu 14 should not be said at all, it has not been supported for a long time, that is, it does not receive updates

**Comment by WMCB-Tech** [comment] 2021-02-01 03:17
@ZhymabekRoman i think this is the root cause of the problem that the old version of dpkg fails when symlink size has changed, usually it is based on this issue

https://github.com/termux/termux-packages/issues/558

As for me i intentionally update the rootfs as possible (via debootstrap) and transfer it

**Comment by WMCB-Tech** [comment] 2021-02-10 01:05
So after toying around with Ubuntu 14.04, i found some problems that would affect the usage experience:

* While installing packages, some of them would cause errors about upstart then fails unless the postinst file is removed

* And also when Installing some packages, it would attempt to create device nodes in `/dev` usually the package `fuse` when i install XFCE

And if this will be added, proot-distro should have the `-L` flag on proot enabled, so far i only tested this flag on my device

---

Centos 7 - I never tried it and it doesn't have tarball for arm64 yet, but it can be possible to use 32-bit one if the Device is 64-bit, although there will be problems when running it though

**Comment by wmcbtech30** [comment] 2022-02-06 10:16
Closing since distributions requesting are outdated. newer ones must be requested instead

**Closed by wmcbtech30** 2022-02-06 10:16 UTC
Labels: enhancement
