### ISSUE TITLE
[Feature]: Using Termux Vulkan-Loaer with PRoot-Dsitro

### ISSUE THREAD

**Issue by hansm629** [termux/proot-distro#402] opened 2024-03-23 17:19 UTC
### Feature description

hello.
Thanks to `Termux+PRoot`, I have built a Linux desktop on my Android Device and am using it well.

There is one thing that is disappointing.
GPU acceleration is limited in SoCs other than the Snapdragon series.

Snapdragon series through `mesa turnip + Termux-X11 DRI3 patch`
GPU acceleration is possible with almost full performance in the `PRoot-Distro Linux environment`, but

Other SoCs (ex: Dimensity, Exynos, Tensor) support GPU acceleration through `virglrenderer-android`, but compatibility and performance are very poor.

In the Termux environment, GPU acceleration is possible by loading the `Android host Vulkan driver` through Vulkan-Loader and implementing WSI through `sysvk & Vulkan WSI Layer`. 
(OpenGL&OpenGL ES acceleration is possible when combined with `mesa zink`, and OpenCL3.0 acceleration is possible when combined with `clvk`)

Technically, in the mid- to long-term, in the PRoot-Distro environment,
Is it possible to load `Termux Vulkan-Loader`?

**Comment by twaik** [comment] 2024-03-23 19:13
Using sysvk and wsi layer is possible because both sysvk and wsi layer are compiled with bionic, and Android libraries (and drivers) are compiled with bionic too. 
In the case of proot using this solution will not be possible because it uses glibc. It is simply not compatible. Using libhybris is not an option because of local thread storage incompatibility of libraries.

**Comment by hansm629** [comment] 2024-03-23 20:47
@twaik 
So, is it okay to recognize that there is no other way to achieve GPU acceleration in a PRoot environment other than the Snapdragon series turnip?

At present, other SoCs do not show satisfactory compatibility in virgl, regardless of performance.

**Comment by twaik** [comment] 2024-03-23 20:49
> So, is it okay to recognize that there is no other way

It does not matter if it is ok or not. We do not have any choise.

**Comment by hansm629** [comment] 2024-03-23 20:53
@twaik 
There will be no choice unless a new, better solution emerges T^T

Or would it be faster to port existing Linux distribution packages to the Termux package?

**Comment by twaik** [comment] 2024-03-23 20:56
> There will be no choice unless a new, better solution emerges T^T

Pull requests are always welcome.

> Or would it be faster to port existing Linux distribution packages to the Termux package?

I do not think so. Our team is pretty much small and can not process such a big amount of packages.

**Comment by hansm629** [comment] 2024-03-23 21:00
@twaik
What do you think about the latest src's angle and virglrenderer?

As sir mentioned before, I am well aware that the latest is not necessarily the best.

However, I thought there might be some improvement in compatibility.

**Comment by twaik** [comment] 2024-03-23 21:01
> What do you think about the latest src's angle and virglrenderer?

I think nothing about it. I do not use this this software.

**Comment by twaik** [comment] 2024-08-12 05:30
Closing this as not going to be implemented.

**Closed by twaik** 2024-08-12 05:30 UTC
Labels: enhancement

**Comment by akku1139** [comment] 2024-12-17 15:50
I was looking for the same thing.

My environment:
- Device; Chromebook
- CPU: Intel Celeron N4500
- Termux: install from Play Store

I tried:
1. Setup Termux
2. Install Arch Linux (x86_64) with proot-distro
3. Login to proot-distro
4. Install `vulkan-icd-loader` and `vulkan-tools`
5. Create `/etc/ld.so.conf.d/android.conf` and run `ldconfig`
```
/usr/lib
/system/lib64
/system/lib
```
6. Create `/usr/share/vulkan/icd.d/android_icd.x86_64.json`
```
{
    "ICD": {
        "api_version": "1.3.296",
        "library_path": "/system/lib64/libvulkan.so"
    },
    "file_format_version": "1.0.0"
}
```
7. Run `vulkaninfo`
```
ERROR: [Loader Message] Code 0 : android.hardware.configstore@1.0.so: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON /system/lib64/libvulkan.so. Ignoring this JSON
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /usr/src/debug/vulkan-tools/Vulkan-Tools-1.4.303/vulkaninfo/./vulkaninfo.h:456:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
```

This seems to be caused by GNU's ld.so not loading libraries whose prefix is ​​not `lib*`.

Arch Linux ldd
```
$ ldd /system/lib64/libvulkan.so
ldd: warning: you do not have execution permission for `/system/lib64/libvulkan.so'
        android.hardware.configstore@1.0.so => not found
        android.hardware.configstore-utils.so => not found
        libziparchive.so => /system/lib64/libziparchive.so (0x0000794526aa2000)
        libhardware.so => /system/lib64/libhardware.so (0x0000794526a9e000)
        libsync.so => /system/lib64/libsync.so (0x0000794526a99000)
        libbase.so => /system/lib64/libbase.so (0x0000794526a58000)
        libhidlbase.so => /system/lib64/libhidlbase.so (0x0000794526999000)
        liblog.so => /system/lib64/liblog.so (0x0000794526985000)
        libui.so => /system/lib64/libui.so (0x0000794526929000)
        libgraphicsenv.so => /system/lib64/libgraphicsenv.so (0x000079452691a000)
        libutils.so => /system/lib64/libutils.so (0x00007945268fa000)
        libcutils.so => /system/lib64/libcutils.so (0x00007945268e1000)
        libz.so => /usr/lib/libz.so (0x00007945268b5000)
        libnativebridge_lazy.so => /system/lib64/libnativebridge_lazy.so (0x00007945268af000)
        libnativeloader_lazy.so => /system/lib64/libnativeloader_lazy.so (0x00007945268aa000)
        libnativewindow.so => /system/lib64/libnativewindow.so (0x00007945268a2000)
        libvndksupport.so => /system/lib64/libvndksupport.so (0x000079452689e000)
        android.hardware.graphics.common@1.0.so => not found
        libSurfaceFlingerProp.so => /system/lib64/libSurfaceFlingerProp.so (0x0000794526885000)
        libc++.so => /system/lib64/libc++.so (0x00007945267db000)
        libc.so => /system/lib64/libc.so (0x0000794526664000)
        libm.so => /system/lib64/libm.so (0x0000794526613000)
        libdl.so => /system/lib64/libdl.so (0x000079452660e000)
        android.hardware.graphics.allocator@2.0.so => not found
        android.hardware.graphics.allocator@3.0.so => not found
        android.hardware.graphics.allocator@4.0.so => not found
        android.hardware.graphics.allocator-V1-ndk.so => not found
        android.hardware.graphics.common-V3-ndk.so => not found
        android.hardware.graphics.common@1.2.so => not found
        android.hardware.graphics.mapper@2.0.so => not found
        android.hardware.graphics.mapper@2.1.so => not found
        android.hardware.graphics.mapper@3.0.so => not found
        android.hardware.graphics.mapper@4.0.so => not found
        libbinder_ndk.so => /system/lib64/libbinder_ndk.so (0x00007945265f2000)
        libgralloctypes.so => /system/lib64/libgralloctypes.so (0x00007945265da000)
        libbinder.so => /system/lib64/libbinder.so (0x0000794526508000)
        libdl_android.so => /system/lib64/libdl_android.so (0x0000794526505000)
        libc.so.6 => /usr/lib/libc.so.6 (0x0000794526314000)
        android.hardware.graphics.common@1.1.so => not found
        android.hardware.configstore-utils.so => not found
        android.hardware.configstore@1.0.so => not found
        android.hardware.configstore@1.1.so => not found
        android.hardware.graphics.common@1.2.so => not found
        ld-android.so => /system/lib64/ld-android.so (0x000079452630f000)
        libandroid_runtime_lazy.so => /system/lib64/libandroid_runtime_lazy.so (0x0000794526309000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x0000500000000000)
        android.hardware.graphics.common-V3-ndk.so => not found
        android.hardware.graphics.mapper@4.0.so => not found
```

Android ldd
```
$ /system/bin/ldd /system/lib64/libvulkan.so
        android.hardware.configstore@1.0.so => /system/lib64/android.hardware.configstore@1.0.so (0x7d88d8f55000)
        android.hardware.configstore-utils.so => /system/lib64/android.hardware.configstore-utils.so (0x7d88d9026000)
        libziparchive.so => /system/lib64/libziparchive.so (0x7d88d8c1c000)
        libhardware.so => /system/lib64/libhardware.so (0x7d88d8b6a000)
        libsync.so => /system/lib64/libsync.so (0x7d88d6fe5000)
        libbase.so => /system/lib64/libbase.so (0x7d88d8896000)
        libhidlbase.so => /system/lib64/libhidlbase.so (0x7d88d8e40000)
        liblog.so => /system/lib64/liblog.so (0x7d88d890d000)
        libui.so => /system/lib64/libui.so (0x7d88d8ccb000)
        libgraphicsenv.so => /system/lib64/libgraphicsenv.so (0x7d88d8b98000)
        libutils.so => /system/lib64/libutils.so (0x7d88d7188000)
        libcutils.so => /system/lib64/libcutils.so (0x7d88d71d6000)
        libz.so => /system/lib64/libz.so (0x7d88d908c000)
        libnativebridge_lazy.so => /system/lib64/libnativebridge_lazy.so (0x7d88d7019000)
        libnativeloader_lazy.so => /system/lib64/libnativeloader_lazy.so (0x7d88d81d6000)
        libnativewindow.so => /system/lib64/libnativewindow.so (0x7d88d8dd4000)
        libvndksupport.so => /system/lib64/libvndksupport.so (0x7d88d8a31000)
        android.hardware.graphics.common@1.0.so => /system/lib64/android.hardware.graphics.common@1.0.so (0x7d88d8aba000)
        libSurfaceFlingerProp.so => /system/lib64/libSurfaceFlingerProp.so (0x7d88d9040000)
        libc++.so => /system/lib64/libc++.so (0x7d88d7069000)
        libc.so => /apex/com.android.runtime/lib64/bionic/libc.so (0x7d88d7e47000)
        libm.so => /apex/com.android.runtime/lib64/bionic/libm.so (0x7d88d89aa000)
        libdl.so => /apex/com.android.runtime/lib64/bionic/libdl.so (0x7d88d90d2000)
        android.hardware.configstore@1.1.so => /system/lib64/android.hardware.configstore@1.1.so (0x7d88d8fa1000)
        android.hardware.graphics.allocator@2.0.so => /system/lib64/android.hardware.graphics.allocator@2.0.so (0x7d88d8184000)
        android.hardware.graphics.allocator@3.0.so => /system/lib64/android.hardware.graphics.allocator@3.0.so (0x7d88d8d8c000)
        android.hardware.graphics.allocator@4.0.so => /system/lib64/android.hardware.graphics.allocator@4.0.so (0x7d88d8e25000)
        android.hardware.graphics.allocator-V1-ndk.so => /system/lib64/android.hardware.graphics.allocator-V1-ndk.so (0x7d88d8168000)
        android.hardware.graphics.common-V3-ndk.so => /system/lib64/android.hardware.graphics.common-V3-ndk.so (0x7d88d8ac5000)
        android.hardware.graphics.common@1.2.so => /system/lib64/android.hardware.graphics.common@1.2.so (0x7d88d8c62000)
        android.hardware.graphics.mapper@2.0.so => /system/lib64/android.hardware.graphics.mapper@2.0.so (0x7d88d8852000)
        android.hardware.graphics.mapper@2.1.so => /system/lib64/android.hardware.graphics.mapper@2.1.so (0x7d88d8d4e000)
        android.hardware.graphics.mapper@3.0.so => /system/lib64/android.hardware.graphics.mapper@3.0.so (0x7d88d8c99000)
        android.hardware.graphics.mapper@4.0.so => /system/lib64/android.hardware.graphics.mapper@4.0.so (0x7d88d7fd9000)
        libbinder_ndk.so => /system/lib64/libbinder_ndk.so (0x7d88d8bd5000)
        libgralloctypes.so => /system/lib64/libgralloctypes.so (0x7d88d8945000)
        libbinder.so => /system/lib64/libbinder.so (0x7d88d8029000)
        libdl_android.so => /apex/com.android.runtime/lib64/bionic/libdl_android.so (0x7d88d8fd3000)
        android.hardware.graphics.common@1.1.so => /system/lib64/android.hardware.graphics.common@1.1.so (0x7d88d8a74000)
        android.hardware.common-V2-ndk.so => /system/lib64/android.hardware.common-V2-ndk.so (0x7d88d8f10000)
        libandroid_runtime_lazy.so => /system/lib64/libandroid_runtime_lazy.so (0x7d88d8b03000)
```

**Comment by twaik** [comment] 2024-12-17 15:54
You can not use bionic libraries from glibc environment...

**Comment by stevefan1999-personal** [comment] 2024-12-19 13:21
@akku1139 I'm also interested in your project because I want to run real Godot Engine (not the half-assed Android version) in Termux, and I knew I will be going into trouble with Bionic so I have setup a proot environment...However it looks like the drivers in the proot environment aren't loadable, and then it turned into llvmpipe fallback...then I realized I don't have vkcube and glxinfo installed in the proot environment, and this is why it shows to use the host GPU info when I was in proot...@twaik Looking for a fix or any recommendation?

**Comment by akku1139** [comment] 2024-12-19 13:56
A temporary solution is to build the software natively in Termux (and install `vulkan-loader-android`)
insted of  using it from a proot-distro.
I ran XMRig OpenCL miner this way and it froze my Chromebook XD

**Comment by akku1139** [comment] 2024-12-21 07:12
Maybe it can be achieved using something like libhybris.
But probably it is very difficult.
